language: node_js
addons:
  sonarcloud:
    organization: "tonimitrevski"
    token:
      secure: 28b62ac329338c3e8db4e63d8c68b57f69a323e1 # encrypted value of your token
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run coverage # Include coverage when running tests
  - npm run build
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
